language: node_js
node_js:
    - "stable"
sudo: false
install:
    - npm install -g tslint tsd eslint eslint-plugin-react
    - npm install
    - tsd install
    - tslint --version
    - eslint --version
script:
    - tsc -p browser/
    - mkdir -p ./build/renderer
    - ./node_modules/.bin/browserify -t babelify -d -o ./build/renderer/index.js ./renderer/index.jsx
    - tslint $(git ls-files | grep '.ts$')
    - eslint $(git ls-files | grep -E '\.jsx?$')
