language: node_js
node_js:
    - "stable"
sudo: false
install:
    - npm install -g tslint tsd eslint eslint-plugin-react electron-prebuilt eslint-plugin-mocha
    - npm install
    - tsd install
    - tslint --version
    - eslint --version
before_script:
    - mkdir -p ./tests/renderer/out
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - ./node_modules/.bin/browserify -t babelify -d -o ./tests/renderer/out/tile-tree_test.js ./tests/renderer/tile-tree_test.js
    - ./node_modules/.bin/browserify -t babelify -d -o ./tests/renderer/out/history_test.js ./tests/renderer/history_test.js
script:
    - tsc -p browser/
    - mkdir -p ./build/renderer
    - ./node_modules/.bin/browserify -t babelify -d -o ./build/renderer/index.js ./renderer/index.jsx
    - tslint $(git ls-files | grep '.ts$')
    - eslint $(git ls-files | grep -E '\.jsx?$')
    - ./node_modules/.bin/electron-mocha --renderer ./tests/renderer/out
